{% set name = "gemoji" %}
{% set version = "4.1.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 734434020cbe964ea9d19086798797a47d23a170892de0ce55b74aa65d2ddc1a

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'
    - gemoji --help

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Character information and metadata for standard and custom emoji.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/github/{{ name }}

extra:
  recipe-maintainers:
    - sodre
