travis:
  secure:
    BINSTAR_TOKEN: MD+1bWhuiTFTOjLt4bfKOrSBs9PX7gbUki7q6YARpfDAsMhRXh3C1r7BFxEaktiudY6HX3mFHHmpFHgKLEoZZxfiovXukKD2KpSAMmjiJH5JGoMVVPrWXToTK/SAIBOJx+wVVOSt1yEo+46XurN+37p2/Y9bDjQ7HyQUmn9wmnFUsyZUut3+ou2MtjudTNQiEf6GsrdFfN52QfdOD3Z4wweuh2m2zhsRhUG2/8g2z7sYcQhUZtKK7G6j1MC5fhYIClAhXcuV1rlln/2Q5h0Vi2IXHg7K+f8lncJFeTrb1CSiLQDwD4J0MIp+iS6KwaQFrG+JpdklhWOPnsKTmogy/Hr3kV2ADoqcGNoiWludjV+gUrTwSaKKKfexKgnS0srUi+XDLUxIVci5DyigXHkFI4Rh8fUwujIXTJxP0obGvPPWWtT3X4sxPR+V1p31BSvIRr+5S5nzfEHI3FmMCJ0vbfcYlyN+ybv+ErbBbPgrrKzEWlRWhajMCHIII3E1JzLWk5Z3cy1R/7sRxxDzunJWoPnOCHjiNLKU8uc7dnG4cfed15W8JNHhSL4ZXYGx9MXThF5bI/T/MTmIajDkixPZioUoTpVdTmO683vTy1qDU+vQGPDRKj3xAoelAluUvihtFnVgVYCDRNzFtmZuGcdVQpUsQta6vDAz3jCe8lBRczQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
